default: &default
  adapter: sqlite3

production:
  adapter: postgresql
  database: db/production

development:
  <<: *default
  adapter: postgresql
  database: 'db/development'

test:
  <<: *default
  database: 'db/test.sqlite'
